CREATE TABLE IF NOT EXISTS admin_rule (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    permission JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);